export function createGameState({ settings, bestScore }){
  return {
    width: 800,
    height: 600,
    player: { x: 400, y: 300, r: 12, color: '#3b82f6', prevX: 400, prevY: 300, vx: 0, vy: 0 },
    drawPlayerX: 400,
    drawPlayerY: 300,
    drawPlayerAngle: 0,
    drawPlayerScale: 1,
    mouse: { x: 400, y: 300 },
    enemies: [],
    lastSpawn: 0,
    spawnInterval: 1000,
    lastTime: 0,
    score: 0,
    best: bestScore,
    running: false,
    speedMultiplier: 1,
    particles: [],
    difficulty: 'normal',
    telegraphs: [],
    survivedCount: 0,
    paused: false,
    debugMode: false,
    debugSandboxMode: false,
    debugInvulnerable: false,
    debugPathLines: false,
    elapsed: 0,
    _lastDOM: 0,
    fps: 0,
    _fpsFrames: 0,
    _fpsLast: 0,
    bullets: [],
    stage: 1,
    stageEase: null,
    boss: null,
    bossActive: false,
    bossPending: false,
    bossTimer: 0,
    bossPendingTimer: 0,
    bossSpawnTele: null,
    // cursor render options (choose shape and scale for the rendered cursor)
    cursorShape: 'square',
    cursorScale: 0.9,
    OBSTACLE_MOUSE_SAFE_PADDING_MIN: 70,
    OBSTACLE_MOUSE_SAFE_PADDING_MULT: 4,
    MAX_OBSTACLE_PLACEMENT_TRIES: 12,
    OBSTACLE_EDGE_PADDING: 40,
    OBSTACLE_SPAWN_MARGIN: 60,
    OBSTACLE_FALLBACK_OFFSET: 80,
    obstacles: [],
    obstacleTelegraphs: [],
    lastObstacleSpawn: 0,
    obstacleActiveInterval: 0,
    nextStageTime: settings.stageDuration,
    pausedBadge: null
  };
}
